// User reducer types
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

// UI reducer types
export const SET_HOME_PAGE = 'SET_HOME_PAGE';
export const SET_HOME_PAGE_QUERY = 'SET_HOME_PAGE_QUERY';
export const SET_FORUM_PAGE = 'SET_FORUM_PAGE';
export const SET_FORUM_PAGE_QUERY = 'SET_FORUM_PAGE_QUERY'
export const SET_USER_PAGE = 'SET_USER_PAGE';
export const SET_FORUM_EXPLORE_PAGE = 'SET_FORUM_EXPLORE_PAGE';
export const SET_FORUM_EXPLORE_PAGE_QUERY = 'SET_FORUM_EXPLORE_PAGE_QUERY'
export const SET_GROUP_EXPLORE_PAGE = 'SET_GROUP_EXPLORE_PAGE';
export const SET_GROUP_PAGE = 'SET_GROUP_PAGE';
export const SET_GROUP_PAGE_QUERY = 'SET_GROUP_PAGE_QUERY';
export const SET_MARKETPLACE_PAGE = 'SET_MARKETPLACE_PAGE';
export const SET_MARKPLACE_PAGE_QUERY = 'SET_MARKETPLACE_PAGE_QUERY';

export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const SET_LIGHT_MODE = 'SET_LIGHT_MODE';
export const SET_DARK_MODE = 'SET_DARK_MODE';

// Data reducer types
export const SET_POSTS = 'SET_POSTS';
export const ADDING_POSTS = 'ADDING_POSTS';
export const ADD_POSTS = 'ADD_POSTS';
export const STOP_ADDING_POSTS = 'STOP_ADDING_POSTS';
export const SET_FORUM_POSTS = 'SET_FORUM_POSTS';
export const LOADING_DATA = 'LOADING_DATA';
export const SET_FORUMS = 'SET_FORUMS';
export const ADDING_FORUMS = 'ADDING_FORUMS';
export const ADD_FORUMS = 'ADD_FORUMS';
export const STOP_ADDING_FORUMS = 'STOP_ADDING_FORUMS';
export const SET_POST = 'SET_POST';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_POST = 'CREATE_POST';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const UPVOTE_POSTS = 'UPVOTE_POST';
export const REMOVE_UPVOTE_POSTS = 'REMOVE_UPVOTE_POST';
export const DOWNVOTE_POSTS = 'DOWNVOTE_POSTS';
export const REMOVE_DOWNVOTE_POSTS = 'REMOVE_DOWNVOTE_POSTS';

export const UPVOTE_COMMENTS = 'UPVOTE_COMMENTS';
export const REMOVE_UPVOTE_COMMENTS = 'REMOVE_UPVOTE_COMMENTS';
export const DOWNVOTE_COMMENTS = 'DOWNVOTE_COMMENTS';
export const REMOVE_DOWNVOTE_COMMENTS = 'REMOVE_DOWNVOTE_COMMENTS';

export const SET_OTHER_USER_DATA = 'SET_OTHER_USER_DATA';

export const SET_FOLLOW = 'SET_FOLLOW_FORUM';
export const SET_UNFOLLOW = 'SET_UNFOLLOW_FORUM';

export const SET_USER_GROUPS = 'SET_USER_GROUPS';

export const SET_GROUP_INFO = 'SET_GROUP_INFO';
export const MAKE_MODERATOR = 'MAKE_MODERATOR';
export const MAKE_MEMBER = 'MAKE_MEMBER';
export const ADD_MEMBER = 'ADD_MEMBER';
export const REMOVE_MEMBER = 'REMOVE_MEMBER';
